### ISSUE TITLE
Missing lib folder

### ISSUE THREAD

**Issue by HimaSava** [antmicro/sodimm-ddr5-tester#1]
Hello,

The lib folder with the KiCAD library file is missing from the repo. Can you please add it to the repo, since I want to use this project as an template for a different project

**Comment by pkatarzynski** [comment]
Hi HimaSava 

The lib folder reference in README is a leftover. Thanks for spotting this - we have amended the README.

With KiCad 7.0 you can simply create component libraries used in the project directly from the design files. 
We recommend this approach as this will give you exactly the same schematic and footrint definitions that are instantiated in the design. 

You can  generate a component library from design files with the following steps: 

* In KiCad Schematic Editor select `File -> Export -> Symbols to New Library` 
  *  Include power symbols, select `Project` for Library Table
  * Confirm you want to reassign the schematic component references to the newly created schematic library
* In KiCad PCB Editor select `File -> Export -> Footprints to New Library`
  * Select `Project` for the Library Table
  * Confirm you want to make the fooprints from the design refer to the newly created footprint library 
 * In KiCad PCB Editor select `Tools -> Update Schematic from PCB`
   * In the `Update` section check only `Footprint assignments` 

This will generate a local library of components that you can then expand on your own.

You may also want to take a  look at https://openhardware.antmicro.com/components/ which shows our collection of KiCad symbols, footprints and Blender models that we used in our designs. Those assets are available in https://github.com/antmicro/hardware-components.
